# -*- coding: utf-8 -*-
"""MagudeswaranPK_2575106_day_1_practise_assignment_solutions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HMVaWr3NKkZvp_GCRNIqswDFZzfdXV_n
"""



"""# **1. Manipulate using a list.**
i) To add new elements to the end of the list
ii) To reverse elements in the list
iii) To display the same list of elements multiple.
iv) To concatenate two list
v) To sort the elements in the list in ascending order.
"""

# i)
list=[11,22,33]
list.append(44)
print('list =',list)

# ii)
list=[1,2,0]
list.reverse()
print('reversed list',list)

# iii)
list=[1,2,11,22,44]
print(list)

# iv)
list1 =[1,2,3]
list2 =[4,5,6]
result = list1+list2
print('list =',result)

# v)
list = [3,1,2,400,100,44,1000,144]
list.sort()
print('sorted list',list)

"""# 2. Write a python program to do in the tuples.
i) Manupulating using tuples.
ii)  To add new elements to the end of the tuples
iii) To reverse elements in the list
iv) To display the elements of the same tuple multiple times.
v) To concatenate two tuples
vi) To sort the elements in the list in ascending order.
"""

# i)
tuple =(1,44,80,300,67)
print('i)',tuple[2])

# ii)
new = 1000
tuple = tuple+(new,)
print('ii)new element added',tuple)

# iii)
reverse = tuple[::-1]
print('iii) reversed elements',reverse)

# iv)
repeat = 3
multiple = tuple * repeat
print('iv) multiple times',multiple)

# v)
tuple1 = (7,8,9)
concatenated = tuple + tuple1
print('v) concatenate two tuples',concatenated)

# vi)
sort =sorted(tuple)
print('vi) sorted elements',sort)

"""# 3. Write a python program to implement the following using list.
i) Create a list with integer(minimum 10 numbers)
ii) How to display the last number in the list
iii) Command for displaying the values from the list[0:4]
iv) Command for displaying the values from the list[2:]
v)  Command for displaying the values from the list[:6]

"""

# i)
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print('i)integer',my_list)

# ii)
last_number = my_list[-1]
print("ii)Last number in the list:", last_number)

# iii)
slice_0_to_4 = my_list[0:4]
print("iii)Values :", slice_0_to_4)

# iv)
slice_from_2 = my_list[2:]
print("iv)Values :", slice_from_2)

# v)
slice_to_6 = my_list[:6]
print("v)Values :", slice_to_6)

"""# Writre a python program: tuple1 =(10,50,20,40,30)
i. To display the elements 10 and 50 From Tuple1.
ii. To display the length of a tuple1.
iii.To find the minimum element from tuple1.
iv. To add all elements in the tuple1.
v. To display the same tuple1 multiple times.
"""

tuple1 = (10, 50, 20, 40, 30)

# i.
print("Elements :", 10,50)

# ii.
print("Length of Tuple1:", len(tuple1))

# iii.
min_element = min(tuple1)
print("Minimum element :", min_element)

# iv.
add_all = sum(tuple1)
print("add all elements :", add_all)

# v.
n = 3
tuple1_multiplied = tuple1 * n
print("multiplie times :", tuple1_multiplied)

"""# 5. Write a python program:
i. To calclate the length of a string
ii. To reverse words in a string
iii. To display the same string multiple times
iv. To concatenate two strings
v. str1="south India", using string slicing  to display "India"
"""

str1 = "south India"

# i.
print("i. length of the string :", len(str1))

# ii.
print("ii. reversed string :", str1[::-1])

# iii.
print("iii. string repeated :",str1 * 3)

# iv.
str2 = "is good"
print("iv. concatenated string :", str1 + str2)

# v.
print("v. :", str1[6:])

