# -*- coding: utf-8 -*-
"""MagudeswaranPK_2575106_day_10_Exercise5_solutions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nHBFfV7kXwgFhCC4_sq8JuTtH7rBfZBB

# Exercise 5
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import pandas as pd

titles = pd.read_csv('/content/titles.csv')
titles.head()

cast = pd.read_csv('/content/cast.csv', index_col=None)
cast.head()

release_dates = pd.read_csv('/content/release_dates.csv', index_col=None,
                                      parse_dates=['date'], infer_datetime_format=True)
release_dates.head()

"""

# Make a bar plot of the months in which movies with "Christmas" in their title tend to be released in the USA."""

stNick = release_dates[release_dates.title.str.contains('Christmas')]
stNick.date.dt.month.value_counts().sort_index().plot(kind='bar')

"""# Make a bar plot of the months in which movies whose titles start with "The Hobbit" are released in the USA."""

rd = release_dates
rd = rd[rd.title.str.startswith('The Hobbit')]
rd = rd[rd.country == 'USA']
rd.date.dt.month.value_counts().sort_index().plot(kind='bar')

"""# Make a bar plot of the day of the week on which movies with "Romance" in their title tend to be released in the USA."""

ronJeremy = release_dates[release_dates.title.str.contains('Romance')]
ronJeremy.date.dt.dayofweek.value_counts().sort_index().plot(kind='bar')

"""# Make a bar plot of the day of the week on which movies with "Action" in their title tend to be released in the USA."""

jamesBond = release_dates[release_dates.title.str.contains('Action')]
jamesBond.date.dt.dayofweek.value_counts().sort_index().plot(kind='bar')

"""
# On which date was each Judi Dench movie from the 1990s released in the USA?"""

judiDench = pd.merge(cast[(cast.name=='Judi Dench')],release_dates[release_dates.country=='USA'])
judiDench[judiDench.year//10 == 199]

"""# In which months do films with Judi Dench tend to be released in the USA?"""

judiDench.date.dt.month.value_counts().sort_index()

"""# In which months do films with Tom Cruise tend to be released in the USA?"""

c = cast
c = c[c.name == 'Tom Cruise']
m = c.merge(usa).sort_values('date')
m.date.dt.month.value_counts().sort_index().plot(kind='bar')